#!/usr/bin/env bash
set -euo pipefail

echo "Cleaning Gradle wrapper caches and project .gradle to force re-download..."

# detect Java major version (handles outputs like 'openjdk version "21.0.1"' or 'java version "1.8.0_201"')
JAVA_MAJOR=$(java -version 2>&1 | sed -E -n 's/.*version "([0-9]+)(\..*)?".*/\1/p' || echo "unknown")
echo "Detected Java major version: ${JAVA_MAJOR}"

# choose a Gradle version compatible with the detected Java
GRADLE_VERSION="8.6"
if [[ "${JAVA_MAJOR}" = "unknown" ]]; then
  echo "Could not detect Java version. Defaulting to Gradle ${GRADLE_VERSION}."
elif [[ "${JAVA_MAJOR}" -ge 21 ]]; then
  GRADLE_VERSION="8.6"
elif [[ "${JAVA_MAJOR}" -ge 17 ]]; then
  GRADLE_VERSION="8.6"
elif [[ "${JAVA_MAJOR}" -ge 11 ]]; then
  GRADLE_VERSION="7.5.1"
else
  # Java 8 or older: use an older Gradle that still supports JDK8
  GRADLE_VERSION="6.7"
fi

echo "Selected Gradle version: ${GRADLE_VERSION}"

WRAPPER_PROPS="/Users/samuelbada/Downloads/rijhub 3/android/gradle/wrapper/gradle-wrapper.properties"
WRAPPER_JAR="/Users/samuelbada/Downloads/rijhub 3/android/gradle/wrapper/gradle-wrapper.jar"
PROJECT_ANDROID_DIR="/Users/samuelbada/Downloads/rijhub 3/android"

# Backup and update gradle-wrapper.properties distributionUrl
if [[ -f "${WRAPPER_PROPS}" ]]; then
  cp -a "${WRAPPER_PROPS}" "${WRAPPER_PROPS}.bak" || true
  # Use macOS-compatible sed -i with .bak; adjust the distributionUrl line
  sed -E -i.bak "s|^distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip|" "${WRAPPER_PROPS}"
  echo "Updated ${WRAPPER_PROPS} -> distributionUrl=https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip"
else
  echo "Warning: gradle-wrapper.properties not found at ${WRAPPER_PROPS}"
fi

# Remove wrapper caches and project .gradle to force re-download
rm -rf "$HOME/.gradle/wrapper/dists" || true
rm -rf "$HOME/.gradle/caches" || true
rm -rf "$HOME/.gradle/daemon" || true
rm -rf "/Users/samuelbada/Downloads/rijhub 3/.gradle" || true

# remove local wrapper jar so the wrapper will re-download the distribution
rm -f "${WRAPPER_JAR}" || true

echo "Removed caches and local wrapper jar."

# --- New: network checks and proxy propagation ---
# Hosts to validate (Google & Maven Central)
HOSTS=(dl.google.com repo.maven.apache.org)

echo "Checking network reachability to Maven/Google hosts..."
for h in "${HOSTS[@]}"; do
  if curl -sS --head --max-time 10 "https://${h}/" >/dev/null 2>&1; then
    echo "  OK: https://${h}"
  else
    echo "  FAIL: https://${h} (curl head failed). Try ping/dig/traceroute or check proxy settings."
  fi
done

# If HTTP(S) proxy env vars exist, write them into Gradle properties (project & user) so Gradle uses them
write_gradle_props() {
  target="$1"
  mkdir -p "$(dirname "$target")"
  echo "# Generated by clean_gradle.sh - proxy/timeouts" > "$target"
  # propagate http proxy if set
  if [[ -n "${HTTP_PROXY:-}" ]]; then
    proto_hostport=$(echo "$HTTP_PROXY" | sed -E 's~https?://~~')
    host=$(echo "$proto_hostport" | sed -E 's~:.*~~')
    port=$(echo "$proto_hostport" | sed -E 's~.*:(.*)~\1~')
    echo "systemProp.http.proxyHost=${host}" >> "$target"
    echo "systemProp.http.proxyPort=${port}" >> "$target"
    echo "systemProp.https.proxyHost=${host}" >> "$target"
    echo "systemProp.https.proxyPort=${port}" >> "$target"
  fi
  if [[ -n "${HTTPS_PROXY:-}" && -z "${HTTP_PROXY:-}" ]]; then
    proto_hostport=$(echo "$HTTPS_PROXY" | sed -E 's~https?://~~')
    host=$(echo "$proto_hostport" | sed -E 's~:.*~~')
    port=$(echo "$proto_hostport" | sed -E 's~.*:(.*)~\1~')
    echo "systemProp.http.proxyHost=${host}" >> "$target"
    echo "systemProp.http.proxyPort=${port}" >> "$target"
    echo "systemProp.https.proxyHost=${host}" >> "$target"
    echo "systemProp.https.proxyPort=${port}" >> "$target"
  fi

  # increase timeouts (milliseconds)
  echo "org.gradle.internal.http.connectionTimeout=60000" >> "$target"
  echo "org.gradle.internal.http.socketTimeout=600000" >> "$target"
  # avoid strict certificate problems in networks with MITM proxies only if explicitly requested
  if [[ "${GRADLE_IGNORE_SSL:-false}" = "true" ]]; then
    echo "systemProp.gradle.insecure=true" >> "$target"
    echo "Note: GRADLE_IGNORE_SSL=true is enabled; this relaxes SSL checks (not recommended)." >&2
  fi
}

# Write project gradle.properties and user gradle.properties
PROJECT_GRADLE_PROPS="${PROJECT_ANDROID_DIR}/gradle.properties"
USER_GRADLE_PROPS="${HOME}/.gradle/gradle.properties"
write_gradle_props "$PROJECT_GRADLE_PROPS"
write_gradle_props "$USER_GRADLE_PROPS"
echo "Wrote proxy/timeouts to:"
echo "  ${PROJECT_GRADLE_PROPS}"
echo "  ${USER_GRADLE_PROPS}"

# --- New: try to pre-download the Gradle distribution zip (retry) to avoid partial/corrupt zip errors ---
if [[ -f "${WRAPPER_PROPS}" ]]; then
  DIST_URL_RAW=$(grep -E '^distributionUrl=' "${WRAPPER_PROPS}" | cut -d'=' -f2- || true)
  # convert escaped colon form https\://... -> https://...
  DIST_URL=$(echo "${DIST_URL_RAW}" | sed 's/\\://g')
  if [[ -n "${DIST_URL}" ]]; then
    echo "Attempting to download Gradle distribution from: ${DIST_URL}"
    # create target directory consistent with Gradle wrapper dists
    ZIP_DIR="$HOME/.gradle/wrapper/dists/gradle-${GRADLE_VERSION}-all"
    mkdir -p "$ZIP_DIR"
    ZIP_NAME="$(basename "${DIST_URL}")"
    ZIP_PATH="${ZIP_DIR}/${ZIP_NAME}"
    # try download with retries if not present or size is suspiciously small
    if [[ -f "$ZIP_PATH" && "$(stat -f%z "$ZIP_PATH" 2>/dev/null || echo 0)" -gt 1000000 ]]; then
      echo "Existing distribution present at ${ZIP_PATH} (size >1MB), skipping download."
    else
      echo "Downloading to ${ZIP_PATH} (retries... )"
      curl -fL --retry 5 --retry-delay 3 --connect-timeout 15 --max-time 600 -o "${ZIP_PATH}.tmp" "${DIST_URL}" || {
        echo "Gradle distribution download failed. Will proceed and let the wrapper attempt download during build."
        rm -f "${ZIP_PATH}.tmp" || true
      }
      if [[ -f "${ZIP_PATH}.tmp" ]]; then
        mv "${ZIP_PATH}.tmp" "${ZIP_PATH}"
        echo "Downloaded Gradle zip to ${ZIP_PATH}"
      fi
    fi
  fi
fi

